### ISSUE TITLE
"No results found" on every search attempt 

### ISSUE THREAD

**Issue by LinaYorda** [Ph4nToM00/FuckFacebook#1]
Hi, I like the tool but somehow I aways getting "no results found". I tried a different combinations of ID, FIRSTNAME, LASTNAME to look for an accounts that I know exist but the tool found nothing. I'm not able to produce any result. 

┌──(kali㉿kali)-[~/FuckFacebook]
└─$ python3 main.py -f Mark  -l Zuckerberg    

                                    By Ph4nToM00
                    🖥  GitHub : https://github.com/Ph4nToM00
                    💵 Paypal : https://www.paypal.me/UnderRadio
No results found.

**Comment by Ph4nToM00** [comment]
Hey, sorry for the response time, this problem has been fixed, now just go through the tor network, reinstall the requirement.txt and everything should work fine


Sincerely
