### ISSUE TITLE
zsh: bad pattern: [-l

### ISSUE THREAD

**Issue by AlexanderSommerFreak** [Ph4nToM00/FuckFacebook#3]
First there is an Error:
ERROR: Could not find a version that satisfies the requirement socket (from versions: none)                                                               
ERROR: No matching distribution found for socket  

and then trying the main.py

└─$ main.py [-l Huber]
zsh: bad pattern: [-l

**Comment by Ph4nToM00** [comment]
the pattern is 

python main.py -l lastname -f firstname without [ ]
